# Default values for istio-bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  selector: ingressgateway
  hostname: example.com

  httpsRedirect: false

  tls:
    enabled: false
    secretName: bookinfo-tls
    gatewayNamespace: istio-system
    acme:
      enabled: false
      certManager:
        version: certmanager.k8s.io/v1alpha1
      renewBefore: 720h
      issuerName: letsencrypt
      issuerKind: ClusterIssuer

productpage:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi
        
details:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi

ratings:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi

reviews:
  replicas: 3
  requests:
    cpu: 300m
    memory: 512Mi
